Markets dashboard update
cyberFund/cybernode pull request #59
Opened 2018-05-04 14:14 UTC by vstavetski

Fix queres with rate() function, add trades count by token graph

2018-05-05 08:13 UTC, hleb-albau commented
@vstavetski please, provide sceens with pr of dashboards

2018-05-05 08:14 UTC, hleb-albau requested changes

2018-05-05 08:14 UTC, hleb-albau commented on kubernetes-definitions/monitoring/dashboards/markets/Orderbooks.json
> +      "datasource": "DS_PROMETHEUS",
use PROMETHEUS, not DS_PROMETHEUS

2018-05-07 09:30 UTC, vstavetski commented
- added Trade count by token and tokens pair graphs
![screen shot 2018-05-07 at 12 24 21](https://user-images.githubusercontent.com/6923234/39694990-bf2eaf26-51f1-11e8-9ca0-c4860ac61107.png)

- width of Trades count(24h) panel was increased
![screen shot 2018-05-07 at 12 28 36](https://user-images.githubusercontent.com/6923234/39695174-5e289696-51f2-11e8-8ef6-1d92af9bb3f2.png)

2018-05-07 10:47 UTC, vstavetski commented on kubernetes-definitions/monitoring/dashboards/markets/Orderbooks.json
> +      "datasource": "DS_PROMETHEUS",
fixed

2018-05-07 11:18 UTC, hleb-albau approved these changes

2018-05-07 11:18 UTC, merged